FROM node:18.18.0

WORKDIR /usr/src/app

# Sao chép package.json và package-lock.json, rồi cài đặt dependencies
COPY package*.json ./
RUN npm install && npm rebuild bcrypt --build-from-source

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Xóa file .env cũ (nếu tồn tại) và tạo file .env mới
RUN rm -f .env && echo "JWT_SECRET=your_jwt_secret" >> .env \
    && echo "DB_NAME=TVU" >> .env \
    && echo "DB_USER=AdminTVU" >> .env \
    && echo "DB_PASSWORD=CongNgheThongTin-DA20TTB" >> .env \
    && echo "DB_HOST=mysql" >> .env \
    && echo "DB_DIALECT=mysql" >> .env \
    && echo "DB_PORT=3306" >> .env

EXPOSE 1509

CMD ["npm", "start"]
